server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bookhouse?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: abc123
  mail:
    host: smtp.qq.com
    username: peng8persevering@vip.qq.com
    password: bnljigdxnthuccda
    default-encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
bookhouse:
  imgPath: \src\main\resources\static\img\

